# Generated by Django 6.0.1 on 2026-01-24 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sending_messages", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "Сообщение", "verbose_name_plural": "Сообщения"},
        ),
        migrations.RenameField(
            model_name="mailing",
            old_name="strat_time",
            new_name="start_time",
        ),
    ]
